export interface SimulationHotspot {
  lat: number;
  lng: number;
  intensity: "low" | "medium" | "high" | "extreme";
  name: string;
}

export interface SimulationDay {
  dayIndex: number;
  dayName: string;
  dateStr: string;
  title: string;
  description: string;
  hazeIntensity: number; // 0 (clear) to 1.0 (heavy haze)
  windDirection: string;
  windSpeed: string;
  hotspotCount: number;
  affectedRegion: string;
  summaryLevel: "Good" | "Moderate" | "Sensitive" | "Unhealthy" | "Very Unhealthy" | "Hazardous";
  // AQI values mapped to each state ID for this simulation day
  stateAqi: Record<string, number>;
  hotspots: SimulationHotspot[];
}

export const HAZE_SIMULATION_DAYS: SimulationDay[] = [
  {
    dayIndex: 0,
    dayName: "Day 1 (Monday)",
    dateStr: "01 Sep 2026",
    title: "Clean Air & Stable Conditions",
    description: "No haze threat detected. Light winds and good air quality recorded across all Malaysian states.",
    hazeIntensity: 0.08,
    windDirection: "Southwest (200°)",
    windSpeed: "8 km/h",
    hotspotCount: 14,
    affectedRegion: "None (All Regions Clean)",
    summaryLevel: "Good",
    stateAqi: {
      "johor": 38,
      "kedah": 42,
      "kelantan": 32,
      "melaka": 40,
      "negeri-sembilan": 36,
      "pahang": 28,
      "penang": 44,
      "perak": 41,
      "perlis": 35,
      "sabah": 26,
      "sarawak": 48,
      "selangor": 45,
      "terengganu": 25,
      "kuala-lumpur": 49,
      "labuan": 22,
      "putrajaya": 43,
    },
    hotspots: [
      { lat: -1.2, lng: 103.5, intensity: "low", name: "South Riau" },
      { lat: -0.8, lng: 109.8, intensity: "low", name: "West Kalimantan" },
    ],
  },
  {
    dayIndex: 1,
    dayName: "Day 2 (Tuesday)",
    dateStr: "02 Sep 2026",
    title: "Hotspot Spike & Initial Smoke Drift",
    description: "Satellite sensors detect peatland fire clusters in Central Sumatra. Smoke begins drifting across the Malacca Straits.",
    hazeIntensity: 0.28,
    windDirection: "Southwest (215°)",
    windSpeed: "14 km/h",
    hotspotCount: 62,
    affectedRegion: "Straits of Malacca, Johor & West Sarawak",
    summaryLevel: "Moderate",
    stateAqi: {
      "johor": 68,
      "kedah": 52,
      "kelantan": 38,
      "melaka": 74,
      "negeri-sembilan": 65,
      "pahang": 42,
      "penang": 58,
      "perak": 62,
      "perlis": 40,
      "sabah": 30,
      "sarawak": 88,
      "selangor": 79,
      "terengganu": 32,
      "kuala-lumpur": 82,
      "labuan": 25,
      "putrajaya": 76,
    },
    hotspots: [
      { lat: -0.5, lng: 102.1, intensity: "medium", name: "Riau Province" },
      { lat: -2.1, lng: 104.2, intensity: "medium", name: "South Sumatra" },
      { lat: -1.4, lng: 110.5, intensity: "medium", name: "West Kalimantan" },
    ],
  },
  {
    dayIndex: 2,
    dayName: "Day 3 (Wednesday)",
    dateStr: "03 Sep 2026",
    title: "Transboundary Haze Intrusion",
    description: "Southwest Monsoon winds transport dense smoke plumes across West Coast Peninsular Malaysia and Western Sarawak.",
    hazeIntensity: 0.58,
    windDirection: "Southwest (225°)",
    windSpeed: "19 km/h",
    hotspotCount: 148,
    affectedRegion: "West Coast Peninsular, Klang Valley & Kuching",
    summaryLevel: "Unhealthy",
    stateAqi: {
      "johor": 118,
      "kedah": 84,
      "kelantan": 48,
      "melaka": 134,
      "negeri-sembilan": 128,
      "pahang": 64,
      "penang": 92,
      "perak": 105,
      "perlis": 54,
      "sabah": 35,
      "sarawak": 142,
      "selangor": 148,
      "terengganu": 40,
      "kuala-lumpur": 152,
      "labuan": 28,
      "putrajaya": 145,
    },
    hotspots: [
      { lat: -0.6, lng: 101.8, intensity: "high", name: "Riau Central Cluster" },
      { lat: -2.8, lng: 104.5, intensity: "high", name: "Palembang Peatlands" },
      { lat: -1.8, lng: 111.2, intensity: "high", name: "Ketapang Kalimantan" },
    ],
  },
  {
    dayIndex: 3,
    dayName: "Day 4 (Thursday)",
    dateStr: "04 Sep 2026",
    title: "Peak Episode & Emergency Alert",
    description: "Peak transboundary haze event. Klang Valley, Melaka, and Kuching exceed 200 AQI triggering school advisory protocols.",
    hazeIntensity: 0.92,
    windDirection: "South-Southwest (210°)",
    windSpeed: "24 km/h",
    hotspotCount: 312,
    affectedRegion: "Klang Valley, Melaka, Negeri Sembilan, Kuching & Samarahan",
    summaryLevel: "Very Unhealthy",
    stateAqi: {
      "johor": 168,
      "kedah": 122,
      "kelantan": 72,
      "melaka": 218,
      "negeri-sembilan": 205,
      "pahang": 110,
      "penang": 142,
      "perak": 165,
      "perlis": 78,
      "sabah": 42,
      "sarawak": 235,
      "selangor": 228,
      "terengganu": 58,
      "kuala-lumpur": 240,
      "labuan": 32,
      "putrajaya": 224,
    },
    hotspots: [
      { lat: -0.4, lng: 101.4, intensity: "extreme", name: "Riau Mega-Fire Cluster" },
      { lat: -1.5, lng: 103.8, intensity: "extreme", name: "Jambi Peat Fire" },
      { lat: -3.0, lng: 104.8, intensity: "extreme", name: "South Sumatra Complex" },
      { lat: -1.9, lng: 110.8, intensity: "extreme", name: "West Kalimantan Border" },
      { lat: -2.6, lng: 112.4, intensity: "extreme", name: "Central Kalimantan Basin" },
    ],
  },
  {
    dayIndex: 4,
    dayName: "Day 5 (Friday)",
    dateStr: "05 Sep 2026",
    title: "Sustained High Haze & Wind Shifts",
    description: "Winds begin shifting slightly southward. Severe air quality persists across central states before cloud seeding operations begin.",
    hazeIntensity: 0.72,
    windDirection: "South (190°)",
    windSpeed: "16 km/h",
    hotspotCount: 220,
    affectedRegion: "Central Peninsular, Perak, Selangor & Sarawak",
    summaryLevel: "Unhealthy",
    stateAqi: {
      "johor": 138,
      "kedah": 115,
      "kelantan": 65,
      "melaka": 165,
      "negeri-sembilan": 158,
      "pahang": 94,
      "penang": 128,
      "perak": 145,
      "perlis": 68,
      "sabah": 38,
      "sarawak": 178,
      "selangor": 172,
      "terengganu": 52,
      "kuala-lumpur": 182,
      "labuan": 29,
      "putrajaya": 170,
    },
    hotspots: [
      { lat: -0.8, lng: 102.2, intensity: "high", name: "Riau Peatlands" },
      { lat: -2.4, lng: 104.1, intensity: "high", name: "South Sumatra Basin" },
      { lat: -2.1, lng: 111.6, intensity: "high", name: "West Kalimantan" },
    ],
  },
  {
    dayIndex: 5,
    dayName: "Day 6 (Saturday)",
    dateStr: "06 Sep 2026",
    title: "Regional Rainfall & Haze Dispersion",
    description: "Convective rainfall in Sumatra and widespread thunderstorms across Peninsular Malaysia significantly disperse smoke plumes.",
    hazeIntensity: 0.35,
    windDirection: "East-Southeast (120°)",
    windSpeed: "11 km/h",
    hotspotCount: 68,
    affectedRegion: "Residual Smoke in Port Klang & Southern Johor",
    summaryLevel: "Moderate",
    stateAqi: {
      "johor": 82,
      "kedah": 68,
      "kelantan": 42,
      "melaka": 88,
      "negeri-sembilan": 84,
      "pahang": 52,
      "penang": 74,
      "perak": 78,
      "perlis": 45,
      "sabah": 32,
      "sarawak": 92,
      "selangor": 95,
      "terengganu": 35,
      "kuala-lumpur": 98,
      "labuan": 24,
      "putrajaya": 91,
    },
    hotspots: [
      { lat: -1.0, lng: 102.8, intensity: "medium", name: "Riau Residual" },
      { lat: -1.6, lng: 111.0, intensity: "medium", name: "West Kalimantan" },
    ],
  },
  {
    dayIndex: 6,
    dayName: "Day 7 (Sunday)",
    dateStr: "07 Sep 2026",
    title: "Full Recovery & Optimal Air Quality",
    description: "Winds normalize and regional rain successfully quenches peatland fires. Air quality index recovers to Good across all 16 states.",
    hazeIntensity: 0.1,
    windDirection: "East (090°)",
    windSpeed: "9 km/h",
    hotspotCount: 18,
    affectedRegion: "None (Full National Recovery)",
    summaryLevel: "Good",
    stateAqi: {
      "johor": 42,
      "kedah": 45,
      "kelantan": 30,
      "melaka": 46,
      "negeri-sembilan": 41,
      "pahang": 32,
      "penang": 48,
      "perak": 44,
      "perlis": 38,
      "sabah": 28,
      "sarawak": 52,
      "selangor": 50,
      "terengganu": 26,
      "kuala-lumpur": 52,
      "labuan": 22,
      "putrajaya": 48,
    },
    hotspots: [
      { lat: -1.5, lng: 103.2, intensity: "low", name: "Riau Coast" },
    ],
  },
];
