export interface MalaysiaDistrict {
  id: string;
  name: string;
  nameMs: string;
  stateId: string;
  stateName: string;
  coordinates: [number, number]; // [lat, lng]
  stationCode: string;
  stationType: "Urban" | "Industrial" | "Suburban" | "Rural" | "Background";
  baseAqiOffset: number; // Variance relative to parent state AQI
  dominantPollutant?: string;
  pm25Offset?: number;
  pm10Offset?: number;
  tempOffset?: number;
  humidityOffset?: number;
}

export const malaysiaDistricts: MalaysiaDistrict[] = [
  // --- SELANGOR (5 Districts) ---
  {
    id: "selangor-shah-alam",
    name: "Shah Alam",
    nameMs: "Shah Alam",
    stateId: "selangor",
    stateName: "Selangor",
    coordinates: [3.0738, 101.5183],
    stationCode: "CAQM-SGR01",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "pm25",
  },
  {
    id: "selangor-petaling-jaya",
    name: "Petaling Jaya",
    nameMs: "Petaling Jaya",
    stateId: "selangor",
    stateName: "Selangor",
    coordinates: [3.1073, 101.6067],
    stationCode: "CAQM-SGR02",
    stationType: "Urban",
    baseAqiOffset: 4,
    dominantPollutant: "pm25",
  },
  {
    id: "selangor-klang",
    name: "Klang",
    nameMs: "Klang",
    stateId: "selangor",
    stateName: "Selangor",
    coordinates: [3.0449, 101.4456],
    stationCode: "CAQM-SGR03",
    stationType: "Industrial",
    baseAqiOffset: 8,
    dominantPollutant: "pm25",
  },
  {
    id: "selangor-banting",
    name: "Banting (Kuala Langat)",
    nameMs: "Banting (Kuala Langat)",
    stateId: "selangor",
    stateName: "Selangor",
    coordinates: [2.8136, 101.5019],
    stationCode: "CAQM-SGR04",
    stationType: "Suburban",
    baseAqiOffset: -3,
    dominantPollutant: "pm25",
  },
  {
    id: "selangor-kuala-selangor",
    name: "Kuala Selangor",
    nameMs: "Kuala Selangor",
    stateId: "selangor",
    stateName: "Selangor",
    coordinates: [3.3524, 101.2504],
    stationCode: "CAQM-SGR05",
    stationType: "Suburban",
    baseAqiOffset: -6,
    dominantPollutant: "pm10",
  },

  // --- KUALA LUMPUR (2 Districts) ---
  {
    id: "kl-cheras",
    name: "Cheras",
    nameMs: "Cheras",
    stateId: "kuala-lumpur",
    stateName: "Kuala Lumpur",
    coordinates: [3.1065, 101.7258],
    stationCode: "CAQM-KUL01",
    stationType: "Urban",
    baseAqiOffset: 2,
    dominantPollutant: "pm25",
  },
  {
    id: "kl-batu-muda",
    name: "Batu Muda",
    nameMs: "Batu Muda",
    stateId: "kuala-lumpur",
    stateName: "Kuala Lumpur",
    coordinates: [3.2078, 101.6836],
    stationCode: "CAQM-KUL02",
    stationType: "Urban",
    baseAqiOffset: -2,
    dominantPollutant: "pm25",
  },

  // --- PUTRAJAYA (1 District) ---
  {
    id: "putrajaya-presint8",
    name: "Presint 8 Putrajaya",
    nameMs: "Presint 8 Putrajaya",
    stateId: "putrajaya",
    stateName: "Putrajaya",
    coordinates: [2.9345, 101.6887],
    stationCode: "CAQM-PJY01",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "o3",
  },

  // --- JOHOR (7 Districts) ---
  {
    id: "johor-larkin",
    name: "Johor Bahru (Larkin)",
    nameMs: "Johor Bahru (Larkin)",
    stateId: "johor",
    stateName: "Johor",
    coordinates: [1.4927, 103.7414],
    stationCode: "CAQM-JHR01",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "pm25",
  },
  {
    id: "johor-pasir-gudang",
    name: "Pasir Gudang",
    nameMs: "Pasir Gudang",
    stateId: "johor",
    stateName: "Johor",
    coordinates: [1.4723, 103.8992],
    stationCode: "CAQM-JHR02",
    stationType: "Industrial",
    baseAqiOffset: 9,
    dominantPollutant: "so2",
  },
  {
    id: "johor-kluang",
    name: "Kluang",
    nameMs: "Kluang",
    stateId: "johor",
    stateName: "Johor",
    coordinates: [2.0251, 103.3328],
    stationCode: "CAQM-JHR03",
    stationType: "Suburban",
    baseAqiOffset: -4,
    dominantPollutant: "pm25",
  },
  {
    id: "johor-batu-pahat",
    name: "Batu Pahat",
    nameMs: "Batu Pahat",
    stateId: "johor",
    stateName: "Johor",
    coordinates: [1.8548, 102.9325],
    stationCode: "CAQM-JHR04",
    stationType: "Urban",
    baseAqiOffset: 2,
    dominantPollutant: "pm25",
  },
  {
    id: "johor-kota-tinggi",
    name: "Kota Tinggi",
    nameMs: "Kota Tinggi",
    stateId: "johor",
    stateName: "Johor",
    coordinates: [1.7381, 103.8999],
    stationCode: "CAQM-JHR05",
    stationType: "Suburban",
    baseAqiOffset: -5,
    dominantPollutant: "pm10",
  },
  {
    id: "johor-segamat",
    name: "Segamat",
    nameMs: "Segamat",
    stateId: "johor",
    stateName: "Johor",
    coordinates: [2.5148, 102.8158],
    stationCode: "CAQM-JHR06",
    stationType: "Suburban",
    baseAqiOffset: -3,
    dominantPollutant: "pm25",
  },
  {
    id: "johor-pengerang",
    name: "Pengerang (PIP)",
    nameMs: "Pengerang (PIP)",
    stateId: "johor",
    stateName: "Johor",
    coordinates: [1.3601, 104.1139],
    stationCode: "CAQM-JHR07",
    stationType: "Industrial",
    baseAqiOffset: 5,
    dominantPollutant: "no2",
  },

  // --- PULAU PINANG (4 Districts) ---
  {
    id: "penang-seberang-jaya",
    name: "Seberang Jaya",
    nameMs: "Seberang Jaya",
    stateId: "penang",
    stateName: "Penang",
    coordinates: [5.3941, 100.3986],
    stationCode: "CAQM-PNG01",
    stationType: "Urban",
    baseAqiOffset: 3,
    dominantPollutant: "pm25",
  },
  {
    id: "penang-minden",
    name: "Minden (USM)",
    nameMs: "Minden (USM)",
    stateId: "penang",
    stateName: "Penang",
    coordinates: [5.3572, 100.3015],
    stationCode: "CAQM-PNG02",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "pm25",
  },
  {
    id: "penang-balik-pulau",
    name: "Balik Pulau",
    nameMs: "Balik Pulau",
    stateId: "penang",
    stateName: "Penang",
    coordinates: [5.3521, 100.2372],
    stationCode: "CAQM-PNG03",
    stationType: "Background",
    baseAqiOffset: -7,
    dominantPollutant: "pm10",
  },
  {
    id: "penang-seberang-perai",
    name: "Seberang Perai",
    nameMs: "Seberang Perai",
    stateId: "penang",
    stateName: "Penang",
    coordinates: [5.3621, 100.4125],
    stationCode: "CAQM-PNG04",
    stationType: "Industrial",
    baseAqiOffset: 6,
    dominantPollutant: "pm25",
  },

  // --- PERAK (5 Districts) ---
  {
    id: "perak-tasek",
    name: "Tasek (Ipoh)",
    nameMs: "Tasek (Ipoh)",
    stateId: "perak",
    stateName: "Perak",
    coordinates: [4.6496, 101.1165],
    stationCode: "CAQM-PRK01",
    stationType: "Industrial",
    baseAqiOffset: 4,
    dominantPollutant: "pm25",
  },
  {
    id: "perak-pegoh",
    name: "Pegoh (Ipoh)",
    nameMs: "Pegoh (Ipoh)",
    stateId: "perak",
    stateName: "Perak",
    coordinates: [4.5458, 101.0776],
    stationCode: "CAQM-PRK02",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "pm25",
  },
  {
    id: "perak-taiping",
    name: "Taiping",
    nameMs: "Taiping",
    stateId: "perak",
    stateName: "Perak",
    coordinates: [4.8517, 100.7381],
    stationCode: "CAQM-PRK03",
    stationType: "Suburban",
    baseAqiOffset: -6,
    dominantPollutant: "pm10",
  },
  {
    id: "perak-seri-manjung",
    name: "Seri Manjung",
    nameMs: "Seri Manjung",
    stateId: "perak",
    stateName: "Perak",
    coordinates: [4.1956, 100.6653],
    stationCode: "CAQM-PRK04",
    stationType: "Urban",
    baseAqiOffset: -2,
    dominantPollutant: "pm25",
  },
  {
    id: "perak-tanjung-malim",
    name: "Tanjung Malim",
    nameMs: "Tanjung Malim",
    stateId: "perak",
    stateName: "Perak",
    coordinates: [3.6828, 101.5204],
    stationCode: "CAQM-PRK05",
    stationType: "Suburban",
    baseAqiOffset: -4,
    dominantPollutant: "pm25",
  },

  // --- KEDAH (4 Districts) ---
  {
    id: "kedah-alor-setar",
    name: "Alor Setar",
    nameMs: "Alor Setar",
    stateId: "kedah",
    stateName: "Kedah",
    coordinates: [6.1248, 100.3678],
    stationCode: "CAQM-KDH01",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "pm25",
  },
  {
    id: "kedah-sungai-petani",
    name: "Sungai Petani",
    nameMs: "Sungai Petani",
    stateId: "kedah",
    stateName: "Kedah",
    coordinates: [5.6435, 100.4883],
    stationCode: "CAQM-KDH02",
    stationType: "Urban",
    baseAqiOffset: 3,
    dominantPollutant: "pm25",
  },
  {
    id: "kedah-kulim",
    name: "Kulim Hi-Tech",
    nameMs: "Kulim Hi-Tech",
    stateId: "kedah",
    stateName: "Kedah",
    coordinates: [5.4194, 100.5739],
    stationCode: "CAQM-KDH03",
    stationType: "Industrial",
    baseAqiOffset: 2,
    dominantPollutant: "pm25",
  },
  {
    id: "kedah-langkawi",
    name: "Langkawi",
    nameMs: "Langkawi",
    stateId: "kedah",
    stateName: "Kedah",
    coordinates: [6.3265, 99.8432],
    stationCode: "CAQM-KDH04",
    stationType: "Background",
    baseAqiOffset: -12,
    dominantPollutant: "o3",
  },

  // --- PERLIS (1 District) ---
  {
    id: "perlis-kangar",
    name: "Kangar",
    nameMs: "Kangar",
    stateId: "perlis",
    stateName: "Perlis",
    coordinates: [6.4449, 100.1985],
    stationCode: "CAQM-PLS01",
    stationType: "Suburban",
    baseAqiOffset: 0,
    dominantPollutant: "pm10",
  },

  // --- NEGERI SEMBILAN (3 Districts) ---
  {
    id: "nsn-seremban",
    name: "Seremban",
    nameMs: "Seremban",
    stateId: "negeri-sembilan",
    stateName: "Negeri Sembilan",
    coordinates: [2.7258, 101.9424],
    stationCode: "CAQM-NSN01",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "pm25",
  },
  {
    id: "nsn-nilai",
    name: "Nilai",
    nameMs: "Nilai",
    stateId: "negeri-sembilan",
    stateName: "Negeri Sembilan",
    coordinates: [2.8169, 101.7961],
    stationCode: "CAQM-NSN02",
    stationType: "Industrial",
    baseAqiOffset: 7,
    dominantPollutant: "pm25",
  },
  {
    id: "nsn-port-dickson",
    name: "Port Dickson",
    nameMs: "Port Dickson",
    stateId: "negeri-sembilan",
    stateName: "Negeri Sembilan",
    coordinates: [2.5228, 101.7959],
    stationCode: "CAQM-NSN03",
    stationType: "Industrial",
    baseAqiOffset: 2,
    dominantPollutant: "so2",
  },

  // --- MELAKA (3 Districts) ---
  {
    id: "melaka-bandaraya",
    name: "Bandaraya Melaka",
    nameMs: "Bandaraya Melaka",
    stateId: "melaka",
    stateName: "Melaka",
    coordinates: [2.1896, 102.2501],
    stationCode: "CAQM-MLK01",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "pm25",
  },
  {
    id: "melaka-bukit-rambai",
    name: "Bukit Rambai",
    nameMs: "Bukit Rambai",
    stateId: "melaka",
    stateName: "Melaka",
    coordinates: [2.2592, 102.1812],
    stationCode: "CAQM-MLK02",
    stationType: "Industrial",
    baseAqiOffset: 6,
    dominantPollutant: "pm25",
  },
  {
    id: "melaka-alor-gajah",
    name: "Alor Gajah",
    nameMs: "Alor Gajah",
    stateId: "melaka",
    stateName: "Melaka",
    coordinates: [2.3854, 102.2089],
    stationCode: "CAQM-MLK03",
    stationType: "Suburban",
    baseAqiOffset: -4,
    dominantPollutant: "pm10",
  },

  // --- PAHANG (5 Districts) ---
  {
    id: "pahang-indera-mahkota",
    name: "Indera Mahkota (Kuantan)",
    nameMs: "Indera Mahkota (Kuantan)",
    stateId: "pahang",
    stateName: "Pahang",
    coordinates: [3.8291, 103.2974],
    stationCode: "CAQM-PHG01",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "pm25",
  },
  {
    id: "pahang-balok-baru",
    name: "Balok Baru (Gebeng)",
    nameMs: "Balok Baru (Gebeng)",
    stateId: "pahang",
    stateName: "Pahang",
    coordinates: [3.9482, 103.3768],
    stationCode: "CAQM-PHG02",
    stationType: "Industrial",
    baseAqiOffset: 8,
    dominantPollutant: "pm25",
  },
  {
    id: "pahang-temerloh",
    name: "Temerloh",
    nameMs: "Temerloh",
    stateId: "pahang",
    stateName: "Pahang",
    coordinates: [3.4485, 102.4172],
    stationCode: "CAQM-PHG03",
    stationType: "Suburban",
    baseAqiOffset: -3,
    dominantPollutant: "pm10",
  },
  {
    id: "pahang-jerantut",
    name: "Jerantut",
    nameMs: "Jerantut",
    stateId: "pahang",
    stateName: "Pahang",
    coordinates: [3.9372, 102.3627],
    stationCode: "CAQM-PHG04",
    stationType: "Rural",
    baseAqiOffset: -6,
    dominantPollutant: "o3",
  },
  {
    id: "pahang-rompin",
    name: "Rompin",
    nameMs: "Rompin",
    stateId: "pahang",
    stateName: "Pahang",
    coordinates: [2.8136, 103.4862],
    stationCode: "CAQM-PHG05",
    stationType: "Rural",
    baseAqiOffset: -5,
    dominantPollutant: "pm10",
  },

  // --- TERENGGANU (4 Districts) ---
  {
    id: "terengganu-kt",
    name: "Kuala Terengganu",
    nameMs: "Kuala Terengganu",
    stateId: "terengganu",
    stateName: "Terengganu",
    coordinates: [5.3117, 103.1324],
    stationCode: "CAQM-TRG01",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "pm25",
  },
  {
    id: "terengganu-kemaman",
    name: "Kemaman",
    nameMs: "Kemaman",
    stateId: "terengganu",
    stateName: "Terengganu",
    coordinates: [4.2341, 103.4244],
    stationCode: "CAQM-TRG02",
    stationType: "Industrial",
    baseAqiOffset: 4,
    dominantPollutant: "so2",
  },
  {
    id: "terengganu-paka",
    name: "Paka (Kerteh)",
    nameMs: "Paka (Kerteh)",
    stateId: "terengganu",
    stateName: "Terengganu",
    coordinates: [4.6378, 103.4361],
    stationCode: "CAQM-TRG03",
    stationType: "Industrial",
    baseAqiOffset: 6,
    dominantPollutant: "no2",
  },
  {
    id: "terengganu-besut",
    name: "Besut",
    nameMs: "Besut",
    stateId: "terengganu",
    stateName: "Terengganu",
    coordinates: [5.7645, 102.5539],
    stationCode: "CAQM-TRG04",
    stationType: "Rural",
    baseAqiOffset: -5,
    dominantPollutant: "pm10",
  },

  // --- KELANTAN (2 Districts) ---
  {
    id: "kelantan-kb",
    name: "Kota Bharu",
    nameMs: "Kota Bharu",
    stateId: "kelantan",
    stateName: "Kelantan",
    coordinates: [6.1254, 102.2386],
    stationCode: "CAQM-KTN01",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "pm25",
  },
  {
    id: "kelantan-tanah-merah",
    name: "Tanah Merah",
    nameMs: "Tanah Merah",
    stateId: "kelantan",
    stateName: "Kelantan",
    coordinates: [5.8089, 102.1467],
    stationCode: "CAQM-KTN02",
    stationType: "Suburban",
    baseAqiOffset: -3,
    dominantPollutant: "pm10",
  },

  // --- SARAWAK (9 Districts) ---
  {
    id: "sarawak-kuching",
    name: "Kuching",
    nameMs: "Kuching",
    stateId: "sarawak",
    stateName: "Sarawak",
    coordinates: [1.5533, 110.3592],
    stationCode: "CAQM-SWK01",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "pm25",
  },
  {
    id: "sarawak-samarahan",
    name: "Samarahan",
    nameMs: "Samarahan",
    stateId: "sarawak",
    stateName: "Sarawak",
    coordinates: [1.4589, 110.4578],
    stationCode: "CAQM-SWK02",
    stationType: "Suburban",
    baseAqiOffset: -4,
    dominantPollutant: "pm25",
  },
  {
    id: "sarawak-sri-aman",
    name: "Sri Aman",
    nameMs: "Sri Aman",
    stateId: "sarawak",
    stateName: "Sarawak",
    coordinates: [1.2372, 111.4621],
    stationCode: "CAQM-SWK03",
    stationType: "Suburban",
    baseAqiOffset: 15,
    dominantPollutant: "pm25",
  },
  {
    id: "sarawak-sibu",
    name: "Sibu",
    nameMs: "Sibu",
    stateId: "sarawak",
    stateName: "Sarawak",
    coordinates: [2.2872, 111.8305],
    stationCode: "CAQM-SWK04",
    stationType: "Urban",
    baseAqiOffset: 5,
    dominantPollutant: "pm25",
  },
  {
    id: "sarawak-bintulu",
    name: "Bintulu",
    nameMs: "Bintulu",
    stateId: "sarawak",
    stateName: "Sarawak",
    coordinates: [3.1762, 113.0435],
    stationCode: "CAQM-SWK05",
    stationType: "Industrial",
    baseAqiOffset: 8,
    dominantPollutant: "pm25",
  },
  {
    id: "sarawak-miri",
    name: "Miri",
    nameMs: "Miri",
    stateId: "sarawak",
    stateName: "Sarawak",
    coordinates: [4.3995, 113.9914],
    stationCode: "CAQM-SWK06",
    stationType: "Urban",
    baseAqiOffset: 2,
    dominantPollutant: "pm25",
  },
  {
    id: "sarawak-mukah",
    name: "Mukah",
    nameMs: "Mukah",
    stateId: "sarawak",
    stateName: "Sarawak",
    coordinates: [2.8984, 112.0917],
    stationCode: "CAQM-SWK07",
    stationType: "Industrial",
    baseAqiOffset: 4,
    dominantPollutant: "pm10",
  },
  {
    id: "sarawak-limbang",
    name: "Limbang",
    nameMs: "Limbang",
    stateId: "sarawak",
    stateName: "Sarawak",
    coordinates: [4.7501, 115.0084],
    stationCode: "CAQM-SWK08",
    stationType: "Rural",
    baseAqiOffset: -10,
    dominantPollutant: "pm10",
  },
  {
    id: "sarawak-kapit",
    name: "Kapit",
    nameMs: "Kapit",
    stateId: "sarawak",
    stateName: "Sarawak",
    coordinates: [2.0167, 112.9333],
    stationCode: "CAQM-SWK09",
    stationType: "Rural",
    baseAqiOffset: -8,
    dominantPollutant: "o3",
  },

  // --- SABAH (5 Districts) ---
  {
    id: "sabah-kk",
    name: "Kota Kinabalu",
    nameMs: "Kota Kinabalu",
    stateId: "sabah",
    stateName: "Sabah",
    coordinates: [5.9804, 116.0735],
    stationCode: "CAQM-SBH01",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "pm25",
  },
  {
    id: "sabah-sandakan",
    name: "Sandakan",
    nameMs: "Sandakan",
    stateId: "sabah",
    stateName: "Sabah",
    coordinates: [5.8402, 118.1179],
    stationCode: "CAQM-SBH02",
    stationType: "Urban",
    baseAqiOffset: -3,
    dominantPollutant: "pm25",
  },
  {
    id: "sabah-tawau",
    name: "Tawau",
    nameMs: "Tawau",
    stateId: "sabah",
    stateName: "Sabah",
    coordinates: [4.2498, 117.8871],
    stationCode: "CAQM-SBH03",
    stationType: "Urban",
    baseAqiOffset: 5,
    dominantPollutant: "pm25",
  },
  {
    id: "sabah-keningau",
    name: "Keningau",
    nameMs: "Keningau",
    stateId: "sabah",
    stateName: "Sabah",
    coordinates: [5.3436, 116.1601],
    stationCode: "CAQM-SBH04",
    stationType: "Suburban",
    baseAqiOffset: -6,
    dominantPollutant: "pm10",
  },
  {
    id: "sabah-kimanis",
    name: "Kimanis",
    nameMs: "Kimanis",
    stateId: "sabah",
    stateName: "Sabah",
    coordinates: [5.5589, 115.9324],
    stationCode: "CAQM-SBH05",
    stationType: "Industrial",
    baseAqiOffset: 4,
    dominantPollutant: "so2",
  },

  // --- LABUAN (1 District) ---
  {
    id: "labuan-main",
    name: "Bandar Labuan",
    nameMs: "Bandar Labuan",
    stateId: "labuan",
    stateName: "Labuan",
    coordinates: [5.2831, 115.2308],
    stationCode: "CAQM-LBN01",
    stationType: "Urban",
    baseAqiOffset: 0,
    dominantPollutant: "pm25",
  },
];

export function getDistrictsByState(stateId: string): MalaysiaDistrict[] {
  return malaysiaDistricts.filter((d) => d.stateId === stateId);
}
